### ISSUE TITLE
Write docs on how to set up the extension including recommendations for regex

### ISSUE THREAD

**Issue by BagToad** [BagToad/Zendesk-Link-Collector#49]
Write docs on how to set up the extension including recommendations for regex

**Comment by kyanny** [comment]
"Getting started" documentation, example in extension option page, or a few concrete example patterns as a default setting would be great for newbies. After installing this extension, I opened a Zendesk ticket with many links in the comments, but didn't see any links in the extension's popup. I didn't understand I need to add patterns manually.

Also, clarifying "RegEx Pattern for what?" is important. After realizing need of adding patterns, I wrote a pattern to match link texts (not link URL) because [output example screenshot](https://github.com/BagToad/Zendesk-Link-Collector?tab=readme-ov-file#link-aggregation) displays link texts, not only URLs. It didn't work, but I wasn't sure what's wrong.

A few ideas with demos:

1. Having concrete example patterns as default

The following patterns are pre-added so that extension users can start getting benefits immediately after the installation. These example patterns also clearly explains what is expected inputs.

![Image](https://github.com/BagToad/Zendesk-Link-Collector/assets/10515/c1be7bac-988c-4dc9-84e0-0c8104421031)

These demo patterns are all "well known" or at least very familiar with the extension users (Zendesk agents), so no concerns to disclose private URLs.

Not sure how it is technically difficult to have default data in browser extension.

2. Showing examples in the options page

Instead of adding default patterns, showing concrete patterns in the options page. In this way, extension users almost immediately know what is expected inputs. Also, they may copy & paste examples instantly.

![Image](https://github.com/BagToad/Zendesk-Link-Collector/assets/10515/b32e8b4a-d31c-405a-82af-fc4aa12830a0)

I prefer this way over having "Getting started" documentation because the examples are displayed very close to the input field so that extension users will notice it without trying to find/read separate documentation. In addition to that, we can make it very concise - no explanations needed as the acceptable regexp is literally there.

**Comment by BagToad** [comment]
Thank you for this @kyanny 🙏 

I think we can do most of this fairly easily. These are all good points. The UX of the extension is definitely something that has been on the backburner for a while as I focus mostly on the extension's functionality. 

Extra thank you for opening #76 😁
